[bar]
order = [ "default", "top" ]

    [bar.default]
    capsule = true
    capsule_padding = 14.0
    capsule_thickness = 0.75999998673796654
    center = [ "widget", "clock", "todo" ]
    end = [ "bar", "caffeine", "session" ]
    font_weight = 900
    margin_ends = 0
    padding = 10
    panel_overlap = 0
    position = "left"
    radius = 30
    radius_bottom_left = 0
    radius_top_left = 0
    shadow = true
    start = [ "clipboard", "screenshot", "battery" ]
    thickness = 58

    [bar.top]
    auto_hide = false
    capsule = true
    capsule_group = []
    capsule_padding = 14.0
    center = [ "workspaces" ]
    enabled = true
    end = [ "keyboard_layout", "ai", "settings" ]
    font_weight = 900
    layer = "top"
    margin_ends = 0
    padding = 10
    panel_overlap = 0
    position = "right"
    radius = 30
    radius_bottom_right = 0
    radius_top_left = 30
    radius_top_right = 0
    reserve_space = true
    show_on_workspace_switch = false
    start = [ "network", "bluetooth", "output_volume" ]
    thickness = 58

[calendar]
enabled = true

[control_center]
hidden_tabs = [ "monitor" ]

    [control_center.calendar]
    show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 32
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
background_opacity = 0.99999997764825821
enabled = true
inactive_opacity = 0.99999997764825821
inactive_scale = 1.0
launcher_position = "none"
layer = "top"
magnification_scale = 1.6000000089406967
pinned = [ "firefox", "org.telegram.desktop", "kitty" ]
position = "bottom"
reserve_space = false
shadow = true

[hot_corners]
enabled = false

    [hot_corners.bottom_left]
    action = "control_center"

    [hot_corners.bottom_right]
    action = "control_center"

    [hot_corners.top_left]
    action = "launcher"

    [hot_corners.top_right]
    action = "launcher"

[location]
address = "Eitorf, Germany"

[lockscreen]
blur_intensity = 0.19999999552965164
tint_intensity = 0.0

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000003" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 82.0
    box_width = 720.0
    cx = 944.0
    cy = 1027.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.0
        background_radius = 0.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 32.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = false
        show_session_buttons = false
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 240.0
    box_width = 656.0
    cx = 944.0
    cy = 868.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = true
        background_color = "on_primary"
        background_opacity = 1.0
        background_padding = 0
        background_radius = 32
        center_text = true
        clock_style = "digital"
        color = "primary"
        font_family = "Google Sans Flex"
        format = "{:%H:%M:%S}"
        shadow = false

[notification]
history_retention_hours = 24
layer = "overlay"
scale = 1.2000000104308128
show_app_name = false

[osd]
background_opacity = 0.99999997764825821

[plugin_settings."h465855hgg/lyrics"]
lyrics_source = "lrclib"
translation_language = "ja"

[plugin_settings."kenn/keybind-cheatsheet"]
cheatsheet_placement = "attached"
compositor = "hyprland"
hyprland_lua_config = "/home/refu/.config/hypr/hyprland/keybinds.lua"
hyprland_parser = "lua"
show_actions = true

[plugin_settings."nightwatch75/todo"]
panel_open_near_click = false

[plugin_settings."yocraft/qrcode"]
generate_button = false
size = 100
titlebar = false

[plugins]
enabled = [ "nightwatch75/file-search", "yuuto/calculator", "yocraft/qrcode", "nightwatch75/todo" ]

[shell]
avatar_path = "/home/lev/Wallpapers/torii.jpg"
button_borders = false
card_borders = false
corner_radius_scale = 1.2500000186264515
font_family = "Google Sans Flex"
popup_shadows = false
screen_time_enabled = true

    [shell.keyboard_layout.custom_labels]
    "English (US)" = "EN"
    Russian = "RU"

    [shell.launcher]
    categories = false
    fetch_exchange_rates = false

        [shell.launcher.providers.calculator]
        global = false

    [shell.panel]
    clipboard_placement = "attached"
    clipboard_position = "auto"
    launcher_placement = "floating"
    open_near_click_clipboard = true
    open_near_click_launcher = true
    open_near_click_wallpaper = false
    polkit_placement = "attached"
    shadow = false
    wallpaper_position = "top_center"

    [shell.screen_corners]
    enabled = true
    size = 30

    [shell.screenshot]
    save_to_file = false
    show_cursor = true

[theme]
builtin = "Tokyo-Night"
community_palette = "Cream"
custom_palette = "torii-ts"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "kitty" ]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
transition = [ "zoom" ]

    [wallpaper.default]
    path = "/home/lev/Pictures/Wallpapers/torii.jpg"

    [wallpaper.last]
    path = "/home/lev/Pictures/Wallpapers/torii.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/refu/Pictures/Wallpapers/torii.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/lev/Pictures/Wallpapers/torii.jpg"

[widget.ai]
glyph = "flare-filled"
scale = 1.5
type = "custom_button"

    [widget.ai.actions]
    left = "exec google-chrome gemini.google.com"

[widget.bar]
scale = 1.5
show_bar_value = false
type = "yuuto/calculator:bar"

[widget.battery]
display_mode = "none"
scale = 1.5

[widget.bluetooth]
scale = 1.5

[widget.brightness]
show_label = false

[widget.caffeine]
scale = 1.5

[widget.clipboard]
scale = 1.5

[widget.clock]
color = "primary"
scale = 1.7

    [widget.clock.actions]
    left = "panel-toggle control-center home"

[widget.control-center]
scale = 1.3

[widget.input_volume]
scale = 1.5
show_label = false

[widget.keyboard_layout]
scale = 1.5
show_glyph = false

[widget.launcher]
scale = 2.0

[widget.network]
scale = 1.5
show_label = false

[widget.output_volume]
scale = 1.5
show_label = false

[widget.screenshot]
glyph = "border-corners"
scale = 1.5

[widget.session]
color = "primary"
scale = 1.5

[widget.settings]
scale = 1.5

    [widget.settings.actions]
    left = "settings-toggle"

[widget.todo]
glyph = "checkbox"
scale = 1.5
type = "nightwatch75/todo:todo"

[widget.tray]
scale = 1.5

[widget.wallpaper]
scale = 1.5

[widget.weather]
scale = 1.5
show_condition = false
show_temperature = true

[widget.widget]
scale = 1.5
type = "yocraft/qrcode:widget"

[widget.workspaces]
active_pill_size = 2.0
scale = 1.5
urgent_color = "secondary"
